-- Schemas

CREATE SCHEMA ACADEMICO;

DROP TABLE ALUNO;
DROP TABLE CATEGORIA;
DROP TABLE CURSO;
DROP TABLE ALUNO_CURSO;

--CRIANDO AS TABELAS DENTRO DE UM SCHEMA

CREATE TABLE academico.aluno (
    id SERIAL PRIMARY KEY,
	primeiro_nome VARCHAR(255) NOT NULL,
	ultimo_nome VARCHAR(255) NOT NULL,
	data_nascimento DATE NOT NULL
);


CREATE TABLE academico.categoria (
    id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE academico.curso (
    id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	categoria_id INTEGER NOT NULL REFERENCES academico.categoria(id)
);


CREATE TABLE academico.aluno_curso (
	aluno_id INTEGER NOT NULL REFERENCES academico.aluno(id),
	curso_id INTEGER NOT NULL REFERENCES academico.curso(id),
	PRIMARY KEY (aluno_id, curso_id)
);

-- Definições em tabelas

DROP TABLE A;

CREATE TEMPORARY TABLE A(
	COLUNA1 VARCHAR(255) NOT NULL CHECK (COLUNA1 <> ''), -- NESSE CASO, O VALOR NÃO PODE SER VAZIO
	COLUNA2 VARCHAR(255) NOT NULL,
	UNIQUE(COLUNA1, COLUNA2)
);


INSERT INTO A  VALUES ('A', 'B');
INSERT INTO A  VALUES ('A', 'B'); -- VAI DAR ERRO, POIS TEM OS MESMOS VALORES
INSERT INTO A  VALUES ('B', 'B');

SELECT * FROM A;

-- Alterando informações

-- RENOMEANDO A TABELA
ALTER TABLE A
RENAME TO TESTE;

SELECT * FROM TESTE;

-- ALTERANDO O NOME DA COLUNA
ALTER TABLE TESTE
RENAME COLUNA1 TO PRIMEIRACOLUNA;

ALTER TABLE TESTE
RENAME COLUNA2 TO SEGUNDACOLUNA;


-- Detalhes do INSERT

-- Em vários bancos '' -> signigica string, já ""-> signifinca campos/coluna

SELECT PRIMEIRA_COLUNA AS "PRIMEIRA COLUNA" FROM TESTE;

-- INSERT SELECT


CREATE TEMPORARY TABLE CURSOS_PROGRAMACAO(
	ID_CURSO INTEGER PRIMARY KEY,
	NOME_CURSO VARCHAR(255) NOT NULL
);


-- Esse insert insere os dados, atráves do select.
INSERT INTO 
SELECT 	ACADEMICO.CURSO.ID,
		ACADEMICO.CURSO.NOME
FROM ACADEMICO.CURSO
	 JOIN ACADEMICO.CATEGORIA ON ACADEMICO.CATEGORIA.ID = ACADEMICO.CURSO.CATEGORIA_ID
	 WHERE CATEGORIA_ID = 2;

-- Importaçao de dados
	
CREATE SCHEMA TESTE;


CREATE TABLE TESTE.CURSOS_PROGRAMACAO(
	ID_CURSO INTEGER PRIMARY KEY,
	NOME_CURSO VARCHAR(255) NOT NULL
);


INSERT INTO TESTE.CURSOS_PROGRAMACAO  
SELECT 	ACADEMICO.CURSO.ID,
		ACADEMICO.CURSO.NOME
FROM ACADEMICO.CURSO
	 JOIN ACADEMICO.CATEGORIA ON ACADEMICO.CATEGORIA.ID = ACADEMICO.CURSO.CATEGORIA_ID
	 WHERE CATEGORIA_ID = 2;
	 
	 
-- ao clicar na tabela, com o direito, a opção de exportar/importar será habilitada, uma nova janela com as opções será aberta, e o usuário irá escolher os campos.

